### ISSUE TITLE
Tinyhttp error in types

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/milliparsec#6]
I have tried to use json() with tinyhttp but it says `nextfunction | undefined` isnt assignable to `nextfunction`. 

A workaround would be
```typescript
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
app.use([(req, res, next) => bodyParser.json()(req, res, next!), logger()]);
```
Which makes sure next function is defnitely defined, however this isn't the best solution to fixing this.

**Comment by talentlessguy** [comment]
What solution would you propose?

**Comment by talentlessguy** [comment]
Can't reproduce, so closing
