### ISSUE TITLE
Add CommonJS support

### ISSUE THREAD

**Issue by Kamrulhasan12345** [talentlessguy/milliparsec#9]
From my starting with nodejs, I have been using CommonJS. And recently, while being at the end of a project, I needed body parsing and installed but unfortunately, it shows a ESM only error. Have any plan for commonjs support? Eagerly waiting for that!

**Comment by talentlessguy** [comment]
Hi,

no, CommonJS support is not planned. In fact, it was removed because CommonJS is a legacy module system that does not follow the ECMA spec.

You should use native esm instead.

If you urgently need CommonJS support, you could try transpiling with Babel.

**Comment by rinsuki** [comment]
If I create pull-request that adds cjs build to this repository, it will be merged? or i should fork project?

context: I tried switch to ESM, but in {"type": "module"} project some tools (like node-dev) are broken or hard to use, and Babel can't (and shouldn't) transpile files in node_modules.

**Comment by talentlessguy** [comment]
@rinsuki everything comes with a price. yeah, most of the tooling is outdated right now or doesn't support modules but it will support them in the near future. so I don't think stepping back in the past is a good idea.

regarding Babel transpiration, see this: https://github.com/babel/babel/issues/8802#issuecomment-454885472

**Comment by talentlessguy** [comment]
also, instead of `node-dev` I'd recommend to use nodemon. it works fine with both `type: module` and mjs
